### ISSUE TITLE
netty-jni-util is incompatible with static compilation

### ISSUE THREAD

**Issue by ejona86** [netty/netty-jni-util#5]
When building statically there is only one copy of netty-jni-util. This means 1) all parts of the binary must use the same version of netty-jni-util and 2) static variables are shared. This is an issue if epoll and tcnative both are in the same static binary.

(1) introduces a bit of a theoretical problem. Since there is no API stability for netty-jni-util we need to make sure that both netty and netty-tcnative releases use the same version of netty-jni-util. Or there's weak enough stability to allow a little version skew between the projects (preferred, isn't always necessary). Either way this is probably easy and close to what might be done anyway, but didn't seem _guaranteed_.

(2) means that either the static variables must be shareable or they must be defined by each consumer of netty-jni-util instead. [`staticPackagePrefix`](https://github.com/netty/netty-jni-util/blob/9e391e13475ffb6c109adadcf185a8d6fa6b86ca/src/main/c/netty_jni_util.c#L46) is not shareable.

Would it be better to define `staticPackagePrefix` in the callers (maybe exposed as one member of a struct) and have it be passed by address to Load/Unload to be maintained by netty-jni-util? Or would it be better to just have the `load_function()` do a strcpy at the end of `load_function()` and store in its own static?

**Comment by normanmaurer** [comment]
@ejona86 I think an `strcpy` might be "easier" ... WDYT ?

**Comment by ejona86** [comment]
SGTM. Sent out #6.

If you do a release of netty-jni-util, I can send a PR for netty-tcnative (I have the changes ready). I don't have a Mac, so it'd be a bit easier if you manage netty, although I can leverage the CI as a slow compiler in a pinch. Epoll wasn't too hard:

```patch
diff --git a/transport-native-epoll/src/main/c/netty_epoll_native.c b/transport-native-epoll/src/main/c/netty_epoll_native.c
index 4c1852f4f3..dc7118f6e3 100644
--- a/transport-native-epoll/src/main/c/netty_epoll_native.c
+++ b/transport-native-epoll/src/main/c/netty_epoll_native.c
@@ -722,13 +722,17 @@ done:
     return ret;
 }
 
-static void netty_epoll_native_JNI_OnUnload(JNIEnv* env, const char* packagePrefix) {
-    netty_epoll_linuxsocket_JNI_OnUnLoad(env, packagePrefix);
+static void netty_epoll_native_JNI_OnUnload(JNIEnv* env) {
+    netty_epoll_linuxsocket_JNI_OnUnLoad(env, staticPackagePrefix);
 
     if (register_unix_called == 1) {
         register_unix_called = 0;
         netty_unix_unregister(env, staticPackagePrefix);
     }
+
+    netty_jni_util_unregister_natives(env, staticPackagePrefix, STATICALLY_CLASSNAME);
+    netty_jni_util_unregister_natives(env, staticPackagePrefix, NATIVE_CLASSNAME);
+
     if (staticPackagePrefix != NULL) {
         free((void *) staticPackagePrefix);
         staticPackagePrefix = NULL;
@@ -741,9 +745,6 @@ static void netty_epoll_native_JNI_OnUnload(JNIEnv* env, const char* packagePref
     packetPortFieldId = NULL;
     packetMemoryAddressFieldId = NULL;
     packetCountFieldId = NULL;
-
-    netty_jni_util_unregister_natives(env, packagePrefix, STATICALLY_CLASSNAME);
-    netty_jni_util_unregister_natives(env, packagePrefix, NATIVE_CLASSNAME);
 }
 
 // Invoked by the JVM when statically linked
```

**Comment by normanmaurer** [comment]
@ejona86 no worries I am on it
